// samples/integrations/react.js/app/containers/App/index.js
import React from 'react';
import StyledComponents from 'styled-components';
import PDFViewer from '../../components/PDFViewer';

const AppWrapper = StyledComponents.div`
    width: 100%;
    height: 100%;
`

export default function App() {
    return (
        <AppWrapper>
            <PDFViewer></PDFViewer>
        </AppWrapper>
    );
}

// samples/integrations/vue.js/src/App.vue
<template>
  <div id="app">
    <PDFViewer/>
  </div>
</template>

<script>
import PDFViewer from './components/PDFViewer.vue'

export default {
  name: 'app',
  components: {
    PDFViewer
  }
}
</script>

<style>
html, body, #app {
  width: 100%;
  height: 100%;
}
#app {
  position: absolute;
}
</style>
